lexer grammar bnfLexer;
IDENTIFIER : [a-z] [a-z0-9_]* ;
CAPITALIZED_WORD : [A-Z] ~[ \t\r\n]* ;
DOUBLE_COLON_EQUAL : '::=' ;
VERTICAL_BAR : '|' ;
LEFT_BRACKET : '[' ;
RIGHT_BRACKET : ']' ;
LEFT_BRACE : '{' ;
RIGHT_BRACE : '}' ;
APOSTROPHE : '\'' -> channel(HIDDEN), mode(STRING_MODE) ;
OTHER : . -> skip ;
mode STRING_MODE;
STRING_TEXT : ~['\\]+ ;
STRING_ESC_SEQ : '\\' ('\'' | '\\') -> type(STRING_TEXT) ;
STRING_APOSTROPHE : '\'' -> channel(HIDDEN), mode(DEFAULT_MODE) ;
STRING_OTHER : . -> skip ;
